spring.application.name=emotion-learning-api

spring.datasource.url=jdbc:postgresql://localhost:5432/emotion_app
spring.datasource.username=emotion_app_user
spring.datasource.password=emotion123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# SQL log
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true